### ISSUE TITLE
Why another OCR plugin?

### ISSUE THREAD

**Issue by papatistos** [kaffarell/obsidian-tesseract-ocr#1]
What are the benefits of this plugin over the existing OCR plugins (Omnisearch, Text Exractor, Obsidian OVR, ...)? No offence! Just curious.

**Comment by kaffarell** [comment]
Ha! Interesting... First time I heard of omnisearch really, looks really good (like a better version of this plugin 🤷). The only advantage of my plugin is that he OCR'd text gets pasted below the image in a hidden tag (< details >). That means you can use the standard obisdian search box instead of a specific plugin command.

**Comment by papatistos** [comment]
Oh, that's interesting. Yes, I see the benefits of having the extracted text in the hidden tag (which, I assume is editable so I can correct mistakes and remove garbage. Or will my changes be overwritten?

I saw that the maintainer of the Text Extractor plugin (on which Omnisearch relies for OCR) [is looking for contributors](https://github.com/scambier/obsidian-text-extractor), so maybe you can submit a PR that integrates that feature as an option into Text extractor?

**Comment by kaffarell** [comment]
> Oh, that's interesting. Yes, I see the benefits of having the extracted text in the hidden tag (which, I assume is editable so I can correct mistakes and remove garbage. Or will my changes be overwritten?

Nope, they will not be overwritten.

> I saw that the maintainer of the Text Extractor plugin (on which Omnisearch relies for OCR) [is looking for contributors (https://github.com/scambier/obsidian-text-extractor), so maybe you can submit a PR that integrates that feature as an option into Text extractor?

I already looked into that... Maybe next week I will open a pr.
