### ISSUE TITLE
Windows Default install only includes ENG

### ISSUE THREAD

**Issue by NBKRedSpy** [kaffarell/obsidian-tesseract-ocr#2]
By default the Windows install for tesseract only includes eng.
This plugin's default of eng+deu will fail in that case.

The docs tell the user to make sure the languages being used are installed, but it will fail silently if deu is also not installed.
This could be confusing to new or less technically inclined users.

`"C:\Users\<User name>\Documents\Obsidian Vault\Pasted image 20230716140637.png" - -l eng+deu
Error opening data file C:\Program Files\Tesseract-OCR/tessdata/deu.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'deu'
I-01 Update Tesseract 5.3.1. Now uses msys`

As per this plugin's notes, changing the language to eng works.

**Comment by kaffarell** [comment]
Hey @NBKRedSpy thanks for opening this issue. Fixed it in version 0.3.7.
