### ISSUE TITLE
Some images wrongly error out

### ISSUE THREAD

**Issue by gauravkumar37** [kaffarell/obsidian-tesseract-ocr#3]
For some images, the plugin is unable to add the text in the `details` tag. This is because sometimes the tesseract program emits a line to stderr: `Estimating resolution as 314`. This debug line makes the plugin think that the command errored out and consequently the OCR text is not added to the details tag even though the console debug logs show the correct text.
If, for example, we add a command-line flag `--dpi 300` to the tesseract command, then the program doesn't emit this stderr line and the plugin works as expected.

**Comment by kaffarell** [comment]
Thanks for opening this issue, should be fixed in this release (0.3.8). Let me know how it goes...
