### ISSUE TITLE
modifying output text placement

### ISSUE THREAD

**Issue by Hamsquishery** [kaffarell/obsidian-tesseract-ocr#4]
I've managed to install & get running OK, and I've edited the main.js so that the text flows, rather than has a hard return at the end of each scan line (I have no coding experience, so it took several tries to find the right bit to tweak, and then undo the tweaks that didn;t work!).
2 things I'm looking for advice on are:
1. Is there an "easy" way to get the text to be placed where I want in my obsidian note (rather than immediately after the image-file reference), and
2. the output text is inserted between the "<details>...</details>" marks: are there any alternatives to this, so I can keep my zotero integration callout in a single callout.

**Comment by kaffarell** [comment]
1) There is no *easy* setting, but I could implement it... shouldn't be too hard. What did you think about? Having an option to put all the text on the bottom of the document?
2) This should be fairly easy to implement, I could add an option called "result-tag", with which you can modify the text surrounding the ocr result. Out of curiosity what would you use here? Another HTML Tag or simply a character?

**Comment by Hamsquishery** [comment]
Hi! 
Sorry it took a while to come back to you on this: I'd posted the query in a few places, and I hadn;t received a notification that you'd responded. Or I did, and I didn't realise where it was from!
The main issue that I've had in working through the obsidian-zotero-ocr threesome I've become obsesssed with in the last week is that when the OCR'd text from an exported image (rather than the highlighted text route) is that it stuffs up the formatting of the callout boxes it's placed in.   
it goes from this: 
![image](https://github.com/kaffarell/obsidian-tesseract-ocr/assets/93463968/cc6e2fa2-7fab-4649-b070-5aa85fce5ce7)
to this:
![image](https://github.com/kaffarell/obsidian-tesseract-ocr/assets/93463968/d58cd196-cb3b-4071-b04d-f7f81eb2eeba)
Ummm...
...Now that's pretty damned embarrassing...
Since asking the question, I've been mucking around inside "it" all for so long now and made so many tweaks to I don't know what that it's not bloody well doing what it was doing that threw me down a garden path I didn't even know was there!
...
Anyway, looking at an earlier version I still hadn't deleted, this was what was happening, where the text after the details block was bumped out of the callout:
before OCR:
![image](https://github.com/kaffarell/obsidian-tesseract-ocr/assets/93463968/c95dffd1-7441-4627-8a41-5b9daecdf497)
After OCR:
![image](https://github.com/kaffarell/obsidian-tesseract-ocr/assets/93463968/7dc4c599-30ea-46e2-959c-9360a9e44040)

I initially worked around it by moving the text that would follow the image + OCR based on the standard templates, to before those elements. That's also better for me, so I can see my comments before I get to the highlight or image

Where I was coming from was to either get the text dropped into a separate md file that I could import later, or the <details> markers changed for something else (maybe even a callout reference on a new line?). I was working through possible options without really knowing what I was after, other than my lit-notes behaving themselves!

Thanks for the response, and please accept my apologies for wasting your time!
Hamish
